apiVersion: apps/v1
kind: Deployment
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  selector:
    matchLabels:
      app: emailservice
  template:
    metadata:
      labels:
        app: emailservice
    spec:
#      serviceAccountName: emailservice
      terminationGracePeriodSeconds: 5
      securityContext:
#        fsGroup: 1000
#        runAsGroup: 1000
        runAsNonRoot: true
        runAsUser: 1000
      containers:
      - name: server
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
              - ALL
          privileged: false
          readOnlyRootFilesystem: true
        image: aditya090/projectk8s:msemailsvc-v1.2
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: DISABLE_PROFILER
          value: "1"
        - name: SMTP_SERVER
          valueFrom:
            configMapKeyRef:
              name: smtp
              key: SMTP_SERVER
        - name: SMTP_PORT
          valueFrom:
            configMapKeyRef:
              name: smtp
              key: SMTP_PORT
        - name: SMTP_USER
          valueFrom:
            configMapKeyRef:
              name: smtp
              key: SMTP_USER

        - name: SMTP_PASS
          valueFrom:
            secretKeyRef:
              name: secretsvc
              key: SMTP_PASS

        - name: DUMMY_MODE
          value: "0"

        - name: ENABLE_REAL_EMAIL
          value: "true"

#        - envFrom:
#            - configMapRef:
#                name: "smtp"
#            -  secretKeyRef:
#                 name: "secretsmtp"
#                  
        readinessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        livenessProbe:
          periodSeconds: 5
          grpc:
            port: 8080
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 128Mi
---
apiVersion: v1
kind: Service
metadata:
  name: emailservice
  labels:
    app: emailservice
spec:
  type: ClusterIP
  selector:
    app: emailservice
  ports:
  - name: grpc
    port: 5000
    targetPort: 8080
---
#apiVersion: v1
#kind: ServiceAccount
#metadata:
#  name: emailservice
